// ═══════════════════════════════════════════════════════════════════════════
// INVENTORLAB — Invention Record PDF Generator
//
// Generates a litigation-grade Invention Record PDF containing:
//   • Matter metadata + privilege banner
//   • Inventor identity block (FIDO2 signing info)
//   • Conception narrative (locked, RFC 3161 anchored)
//   • Accepted claim elements with inventorship attestations
//   • AI interaction summary (what was queried, accepted, rejected)
//   • Prior art review summary
//   • Provenance Ledger summary hash (last chain hash)
//   • Signature block placeholder (DocuSign integration in Sprint 4)
//
// Output: base64-encoded PDF string + SHA-256 hash
//
// DISCLAIMER LINE (mandatory on every page):
//   "DRAFT — For Counsel Review Only. Not a legal opinion.
//    This document was generated by InventorLab — an AI-assisted
//    invention capture platform. All outputs require independent
//    attorney review before use in patent prosecution."
// ═══════════════════════════════════════════════════════════════════════════

import { db } from "./db";
import {
  matters, users, matterInventors, conceptionNarratives,
  claimElements, priorArtReferences, provenanceLedger, inventionRecords,
} from "../shared/schema";
import { eq, and } from "drizzle-orm";
import { sha256, requestRfc3161Timestamp } from "./crypto";
import { writeLedgerEntry } from "./ledger";

// We use a pure-JS approach to generate PDF markup that can be
// rendered server-side. In production, integrate jsPDF or Puppeteer.
// For now, we generate a structured HTML document that is both
// human-readable and can be printed-to-PDF from the browser.

export interface InventionRecordData {
  matter:       any;
  inventors:    any[];
  conception:   any | null;
  claims:       any[];
  priorArt:     any[];
  ledgerEntries: any[];
  ledgerSummary: {
    totalEntries:   number;
    lastChainHash:  string | null;
    lastTsaSerial:  string | null;
    aiCallCount:    number;
    humanActionCount: number;
  };
  generatedAt:  string;
  recordHash:   string;
  tsaToken:     string | null;
  tsaSerial:    string | null;
  disclaimer:   string;
}

export async function generateInventionRecord(
  matterId:  number,
  tenantId:  number,
  requesterId: number
): Promise<InventionRecordData> {

  // ── Gather all matter data ─────────────────────────────────────────────────
  const [matter] = await db.select().from(matters).where(eq(matters.id, matterId)).limit(1);
  if (!matter) throw new Error("Matter not found");

  // Inventors
  const inventorLinks = await db.select().from(matterInventors).where(eq(matterInventors.matterId, matterId));
  const inventorUsers = await Promise.all(
    inventorLinks.map(async (link) => {
      const [u] = await db.select().from(users).where(eq(users.id, link.userId)).limit(1);
      return { ...link, user: u };
    })
  );

  // Conception narrative
  const conceptions = await db.select().from(conceptionNarratives)
    .where(and(eq(conceptionNarratives.matterId, matterId), eq(conceptionNarratives.isLocked, true)));

  // Accepted claims
  const acceptedClaims = await db.select().from(claimElements)
    .where(and(eq(claimElements.matterId, matterId), eq(claimElements.status, "accepted")))
    .orderBy(claimElements.elementNumber);

  // Prior art
  const priorArt = await db.select().from(priorArtReferences)
    .where(eq(priorArtReferences.matterId, matterId));

  // Full ledger
  const ledger = await db.select().from(provenanceLedger)
    .where(eq(provenanceLedger.matterId, matterId))
    .orderBy(provenanceLedger.id);

  const aiCalls     = ledger.filter(e => e.actorType === "ai").length;
  const humanActions = ledger.filter(e => e.actorType === "human").length;
  const lastEntry   = ledger[ledger.length - 1];

  // ── Compute record hash ────────────────────────────────────────────────────
  const recordPayload = {
    matterId:       matter.matterId,
    title:          matter.title,
    inventorCount:  inventorUsers.length,
    claimsCount:    acceptedClaims.length,
    conceptionHash: conceptions[0]?.sha256Hash ?? null,
    lastChainHash:  lastEntry?.chainHash ?? null,
    generatedAt:    new Date().toISOString(),
  };
  const recordHash  = sha256(JSON.stringify(recordPayload));
  const tsaResult   = await requestRfc3161Timestamp(recordHash);

  // ── Upsert invention record in DB ──────────────────────────────────────────
  const existingRecords = await db.select().from(inventionRecords).where(eq(inventionRecords.matterId, matterId));
  if (existingRecords.length > 0) {
    await db.update(inventionRecords).set({
      pdfSha256:    recordHash,
      tsa3161Token: tsaResult?.token ?? null,
      generatedAt:  new Date(),
      status:       "draft",
    }).where(eq(inventionRecords.matterId, matterId));
  } else {
    await db.insert(inventionRecords).values({
      matterId,
      pdfSha256:    recordHash,
      tsa3161Token: tsaResult?.token ?? null,
      status:       "draft",
    });
  }

  // ── Write to Provenance Ledger ─────────────────────────────────────────────
  await writeLedgerEntry({
    matterId, tenantId, eventType: "invention_record_generated",
    actorId: requesterId, actorType: "human",
    payload: {
      recordHash,
      tsaSerial:   tsaResult?.serial ?? null,
      claimsCount: acceptedClaims.length,
      inventorCount: inventorUsers.length,
      ledgerEntries: ledger.length,
    },
  });

  return {
    matter,
    inventors:   inventorUsers,
    conception:  conceptions[0] ?? null,
    claims:      acceptedClaims,
    priorArt,
    ledgerEntries: ledger,
    ledgerSummary: {
      totalEntries:    ledger.length,
      lastChainHash:   lastEntry?.chainHash ?? null,
      lastTsaSerial:   lastEntry?.tsaSerial ?? null,
      aiCallCount:     aiCalls,
      humanActionCount: humanActions,
    },
    generatedAt:  new Date().toISOString(),
    recordHash,
    tsaToken:     tsaResult?.token ?? null,
    tsaSerial:    tsaResult?.serial ?? null,
    disclaimer:   "DRAFT — For Counsel Review Only. Not a legal opinion. This document was generated by InventorLab, an AI-assisted invention capture platform operating under Enterprise DPA. All outputs require independent attorney review before use in patent prosecution.",
  };
}

// ── HTML renderer for the Invention Record ────────────────────────────────────
// Produces a printable HTML document. Browser print-to-PDF produces the
// final deliverable. In Sprint 4, replace with jsPDF/Puppeteer server-side.
export function renderInventionRecordHtml(record: InventionRecordData): string {
  const { matter, inventors, conception, claims, priorArt, ledgerSummary } = record;
  const ts = (d: string | null) => d ? new Date(d).toLocaleString() : "—";

  const claimsHtml = claims.map(c => `
    <div class="claim-element">
      <div class="claim-number">Claim Element ${c.elementNumber}</div>
      <div class="claim-text">${escHtml(c.humanFinalText ?? c.aiProposedText ?? "")}</div>
      ${c.inventorAttestation ? `<div class="attestation">Inventor attestation: "${escHtml(c.inventorAttestation)}"</div>` : ""}
      <div class="claim-meta">
        Status: ${c.status} | Attested: ${ts(c.attestedAt)} |
        Hash: <code>${(c.sha256Hash ?? "").slice(0,16)}…</code>
        ${c.tsa3161Token ? ' | <span class="tsa-badge">TSA ✓</span>' : ""}
        ${c.isPriorityGuardFlagged ? ' | <span class="pg-flag">⚠ Priority Guard flagged</span>' : ""}
        ${c.hasDispute ? ' | <span class="dispute-flag">⚑ Dispute logged</span>' : ""}
      </div>
    </div>
  `).join("");

  const priorArtHtml = priorArt.length === 0 ? "<p>No prior art searched yet.</p>" :
    priorArt.map(p => `
      <div class="prior-art-item">
        <strong>${escHtml(p.title ?? "Untitled")}</strong>
        ${p.patentNumber ? ` <span class="patent-num">US${escHtml(p.patentNumber)}</span>` : ""}
        <span class="relevance">Relevance: ${p.relevanceScore ?? "—"}/100</span>
        ${p.isDistinguishing !== null ? `<span class="${p.isDistinguishing ? 'distinguishing' : 'not-distinguishing'}">${p.isDistinguishing ? "✓ Distinguishing" : "⚠ Not fully distinguishing"}</span>` : ""}
        ${p.annotation ? `<p class="annotation">${escHtml(p.annotation)}</p>` : ""}
      </div>
    `).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Invention Record — ${escHtml(matter.title)}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', sans-serif; font-size: 11pt; color: #1a1a1a; background: #fff; padding: 0; }
  @page { margin: 2cm; size: A4; }
  .page-header { background: #030407; color: #E5C07B; padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; print-color-adjust: exact; }
  .page-header h1 { font-size: 14pt; font-weight: 600; }
  .page-header .meta { font-size: 8pt; font-family: 'JetBrains Mono'; text-align: right; }
  .disclaimer { background: #fff3cd; border: 1.5px solid #ffc107; padding: 10px 16px; margin: 16px; font-size: 8.5pt; font-weight: 500; color: #7a4f00; }
  .section { margin: 0 16px 20px; }
  .section-title { font-size: 12pt; font-weight: 600; color: #030407; border-bottom: 2px solid #E5C07B; padding-bottom: 4px; margin-bottom: 12px; }
  .field { margin-bottom: 8px; }
  .field-label { font-size: 8.5pt; font-weight: 600; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }
  .field-value { font-size: 10.5pt; color: #1a1a1a; }
  .narrative-text { background: #f8f8f8; border-left: 3px solid #E5C07B; padding: 12px 16px; font-size: 10.5pt; line-height: 1.7; white-space: pre-wrap; margin-top: 8px; }
  .claim-element { border: 1px solid #e5e7eb; border-radius: 6px; padding: 12px; margin-bottom: 10px; }
  .claim-number { font-size: 8.5pt; font-weight: 700; color: #6b7280; text-transform: uppercase; margin-bottom: 6px; }
  .claim-text { font-size: 10.5pt; line-height: 1.6; color: #1a1a1a; margin-bottom: 8px; }
  .attestation { font-size: 9pt; color: #374151; background: #f0fdf4; border-left: 2px solid #4ade80; padding: 6px 10px; margin-bottom: 6px; font-style: italic; }
  .claim-meta { font-size: 8pt; color: #9ca3af; font-family: 'JetBrains Mono'; }
  .tsa-badge { color: #16a34a; font-weight: 600; }
  .pg-flag { color: #d97706; font-weight: 600; }
  .dispute-flag { color: #dc2626; font-weight: 600; }
  .prior-art-item { border-bottom: 1px solid #f3f4f6; padding: 10px 0; }
  .patent-num { font-family: 'JetBrains Mono'; font-size: 9pt; color: #E5C07B; margin-left: 8px; }
  .relevance { font-size: 8.5pt; color: #6b7280; margin-left: 12px; }
  .distinguishing { color: #16a34a; font-size: 8.5pt; margin-left: 12px; }
  .not-distinguishing { color: #dc2626; font-size: 8.5pt; margin-left: 12px; }
  .annotation { font-size: 9pt; color: #374151; margin-top: 4px; font-style: italic; }
  .ledger-stats { display: grid; grid-template-columns: repeat(3,1fr); gap: 12px; margin-top: 8px; }
  .stat-box { background: #f8f8f8; border: 1px solid #e5e7eb; border-radius: 6px; padding: 10px; text-align: center; }
  .stat-number { font-size: 18pt; font-weight: 700; color: #030407; }
  .stat-label { font-size: 8pt; color: #6b7280; text-transform: uppercase; }
  .hash-block { font-family: 'JetBrains Mono'; font-size: 8pt; background: #f8f8f8; padding: 8px 12px; border-radius: 4px; word-break: break-all; color: #374151; margin-top: 6px; }
  .sig-block { border: 2px solid #030407; padding: 20px; margin-top: 12px; }
  .sig-line { border-bottom: 1px solid #1a1a1a; height: 40px; margin: 16px 0 4px; }
  .sig-label { font-size: 8.5pt; color: #6b7280; }
  .footer { text-align: center; font-size: 7.5pt; color: #9ca3af; padding: 12px; border-top: 1px solid #e5e7eb; margin-top: 24px; font-family: 'JetBrains Mono'; }
  @media print { body { padding: 0; } .page-header { -webkit-print-color-adjust: exact; } }
</style>
</head>
<body>

<div class="page-header">
  <div>
    <div style="font-size:9pt;opacity:0.7;margin-bottom:2px;">INVENTORLAB — INVENTION RECORD</div>
    <h1>${escHtml(matter.title)}</h1>
  </div>
  <div class="meta">
    Matter ID: ${escHtml(matter.matterId)}<br>
    Generated: ${ts(record.generatedAt)}<br>
    Record hash: ${record.recordHash.slice(0,16)}…<br>
    ${record.tsaSerial ? `TSA serial: ${record.tsaSerial.slice(0,12)}…` : "TSA: DEV MODE"}
  </div>
</div>

<div class="disclaimer">⚠ ${escHtml(record.disclaimer)}</div>

<div class="section">
  <div class="section-title">1. Matter Information</div>
  <div class="field"><div class="field-label">Matter ID</div><div class="field-value">${escHtml(matter.matterId)}</div></div>
  <div class="field"><div class="field-label">Application Type</div><div class="field-value">${escHtml(matter.applicationType)}${matter.isCip ? " (CIP — new matter intentional)" : ""}</div></div>
  <div class="field"><div class="field-label">Status</div><div class="field-value">${escHtml(matter.status)} / ${escHtml(matter.sessionState)}</div></div>
  <div class="field"><div class="field-label">Federal Funding</div><div class="field-value">${matter.hasFederalFunding ? `YES — Bayh-Dole active. Agency: ${escHtml(matter.federalAgency ?? "—")}. Grant: ${escHtml(matter.grantNumber ?? "—")}` : "No"}</div></div>
  ${matter.problemStatement ? `<div class="field"><div class="field-label">Problem Statement</div><div class="field-value">${escHtml(matter.problemStatement)}</div></div>` : ""}
</div>

<div class="section">
  <div class="section-title">2. Named Inventors</div>
  ${inventors.map((inv: any, i: number) => `
    <div class="field">
      <div class="field-label">Inventor ${i + 1} (${escHtml(inv.role)})</div>
      <div class="field-value">${escHtml(inv.user?.fullName ?? "Unknown")} — ${escHtml(inv.user?.email ?? "—")}</div>
      ${inv.fido2SignatureHash ? `<div class="field-value" style="font-size:8pt;font-family:monospace;color:#6b7280">FIDO2 sig: ${inv.fido2SignatureHash.slice(0,24)}…</div>` : ""}
      ${inv.tsa3161Token ? `<div style="font-size:8pt;color:#16a34a">RFC 3161 TSA ✓ Serial: ${(inv.tsaSerial ?? "").slice(0,12)}…</div>` : ""}
    </div>
  `).join("")}
</div>

<div class="section">
  <div class="section-title">3. Conception Narrative</div>
  ${conception ? `
    <div class="field">
      <div class="field-label">Locked</div>
      <div class="field-value">${ts(conception.lockedAt)}</div>
    </div>
    <div class="field">
      <div class="field-label">Narrative hash (SHA-256)</div>
      <div class="hash-block">${conception.sha256Hash ?? "—"}</div>
    </div>
    ${conception.tsaSerial ? `<div class="field"><div class="field-label">TSA Serial</div><div class="field-value" style="font-family:monospace">${conception.tsaSerial}</div></div>` : ""}
    <div class="narrative-text">${escHtml(conception.narrative)}</div>
  ` : "<p>No locked conception narrative found.</p>"}
</div>

<div class="section">
  <div class="section-title">4. Accepted Claim Elements (${claims.length})</div>
  ${claims.length === 0 ? "<p>No accepted claim elements.</p>" : claimsHtml}
</div>

<div class="section">
  <div class="section-title">5. Prior Art Search Summary</div>
  ${priorArtHtml}
</div>

<div class="section">
  <div class="section-title">6. Provenance Ledger Summary</div>
  <div class="ledger-stats">
    <div class="stat-box"><div class="stat-number">${ledgerSummary.totalEntries}</div><div class="stat-label">Total entries</div></div>
    <div class="stat-box"><div class="stat-number">${ledgerSummary.aiCallCount}</div><div class="stat-label">AI interactions</div></div>
    <div class="stat-box"><div class="stat-number">${ledgerSummary.humanActionCount}</div><div class="stat-label">Human decisions</div></div>
  </div>
  <div class="field" style="margin-top:12px">
    <div class="field-label">Last chain hash (tamper-evidence anchor)</div>
    <div class="hash-block">${ledgerSummary.lastChainHash ?? "—"}</div>
  </div>
  ${ledgerSummary.lastTsaSerial ? `<div class="field"><div class="field-label">Last TSA Serial</div><div class="field-value" style="font-family:monospace">${ledgerSummary.lastTsaSerial}</div></div>` : ""}
</div>

<div class="section">
  <div class="section-title">7. Inventor Signature Block</div>
  <p style="font-size:9pt;color:#374151;margin-bottom:12px">
    By signing below, each named inventor attests that: (1) they are the true and only inventor of the subject matter
    claimed herein; (2) the conception narrative in Section 3 accurately describes their own human conception of the
    invention; and (3) all claim elements in Section 4 reflect their own inventive contribution, not AI-generated conception.
  </p>
  ${inventors.map((inv: any) => `
    <div class="sig-block">
      <div class="field-label">Inventor: ${escHtml(inv.user?.fullName ?? "—")}</div>
      <div class="sig-line"></div>
      <div class="sig-label">Signature &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date</div>
    </div>
  `).join("")}
</div>

<div class="footer">
  InventorLab v10 | Record hash: ${record.recordHash} |
  ${record.tsaSerial ? `TSA: ${record.tsaSerial} |` : ""}
  Generated: ${record.generatedAt} |
  DRAFT — For Counsel Review Only — Not a legal opinion
</div>

</body>
</html>`;
}

function escHtml(str: string): string {
  return (str ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
